function contentListBookCss(){
  let pageLeft = $q("#pageLeft");
  let pageRight = $q("#pageRight");

  let contentPageLeft = 
  "<h1>Libro de CSS</h1>"
  +"<ul>"
    +'<li class="liClass liBookSkyBlue">'
      +'<input type="checkbox" id="BackGrad" name="optionBookCSS" value="BackGrad"/>'
      +'<label for="BackGrad" onmouseenter="hover(this);" onmouseleave="unHover(this)" >Backgrounds Gradients</label>'
    +'</li>'
    +'<li class="liClass liBookSkyBlue">'
      +'<input type="checkbox" id="BordGrad" name="optionBookCSS" value="BordGrad" />'
      +'<label for="BordGrad"onmouseenter="hover(this); " onmouseleave="unHover(this)" >Borders Gradients</label>'
    +'</li>'
    +'<li class="liClass liBookSkyBlue">'
      +'<input type="checkbox" id="ColorTextGrad" name="optionBookCSS" value="ColorTextGrad" />'
      +'<label for="ColorTextGrad" onmouseenter="hover(this); " onmouseleave="unHover(this)" >Color Text Gradients</label>'
    +'</li>'
    +'<li class="liClass liBookSkyBlue">'
      +'<input type="checkbox" id="3DObjects" name="optionBookCSS" value="3DObjects" />'
      +'<label for="3DObjects" onmouseenter="hover(this); " onmouseleave="unHover(this)" >3D Objects</label>'
    +'</li>'
    +'<li class="liClass liBookSkyBlue">'
      +'<input type="checkbox" id="CenterDiv" name="optionBookCSS" value="CenterDiv" />'
      +'<label for="CenterDiv" onmouseenter="hover(this);" onmouseleave="unHover(this)">Center Div</label>'
    +'</li>'
  +"</ul>";
  
  pageRight.innerHTML = "<div style='height: 100%; width: 100%; display: grid; align-content: center; text-align: center; position: relative; right: -5%; font-size: 20px; font-weight: 700;'>posiciónese sobre alguno de los items</div>"
  //document.getElementById("pageLeft").innerHTML(contentPageLeft);
  pageLeft.innerHTML = contentPageLeft;
  
  // Obtén todos los checkboxes dentro del contenedor específico por su nombre
  const container = document.getElementById('pageLeft'); // Reemplaza 'containerID' con el ID de tu contenedor
  const checkboxes = container.querySelectorAll('input[type="checkbox"][name="optionBookCSS"]');

  // Agrega un evento clic a cada checkbox
  checkboxes.forEach(function(checkbox) {
      checkbox.addEventListener('click', function() {
          // Deselecciona todos los checkboxes excepto el actual
          checkboxes.forEach(function(otherCheckbox) {
              if (otherCheckbox !== checkbox) {
                  otherCheckbox.checked = false;
              }
          });
      });
  });
}


function backGradSelected(){
  let htmlContentPageRight = '<style>'
  +'.gradient{'
    +'height:100px;'
    +'width:100px;'
  +'}'
  +'.linear_gradient1{'
    +'background:linear-gradient(316deg, #ff0058,#03a9f4);'
  +'}'
  +'.radial_gradient1{'
    +'background:radial-gradient(#ff0058,#03a9f4);'
  +'}'
  +'.linear_gradient2{'
    +'background:linear-gradient(316deg, #f05bf1,#03a9f4);'
  +'}'
  +'.radial_gradient2{'
    +'background:radial-gradient(#f05bf1,#03a9f4);'
  +'}'
  +'.linear_gradient3{'
    +'background:linear-gradient(45deg, #ffbc00, #ff0058);'
  +'}'
  +'.radial_gradient3{'
    +'background:radial-gradient(#ffbc00, #ff0058);'
  +'}'
  +'.linear_gradient4{'
    +'background:linear-gradient(316deg, #4dff03,#03a9f4);'
  +'}'
  +'.radial_gradient4{'
    +'background:radial-gradient(#4dff03,#03a9f4);'
  +'}'
  +'.conic_gradient1{'
    +'background:conic-gradient(#5e5e5e,#3a3a3a, #181818,#181818, #3a3a3a,#5e5e5e,#3a3a3a,#181818,#181818,#3a3a3a,#5e5e5e);'
  +'}'
  +'.conic_gradient2{'
    +'background: conic-gradient(#c5dee5,#79a0ab, #607e87,#607e87, #79a0ab,#C5DDE5,#79a0ab,#607e87,#607e87,#79a0ab,#c5dee5);'
  +'}'
  +'.circular{'
    +'border-radius:50px;'
  +'}'
  +'tr{'
    +'display: flex;'
  +'}'
  +'td{'
    +'align-content: center;'
    +'display: grid;'
    +'place-items: center;'
    +'text-align: center;'
    +'margin: 10px;'
  +'}'
  +'.container{'
    +'height: 310px;'
    +'width: 250px;'
  +'}'
  +'.container .frame{'
    +'position:relative;'
    +'background: linear-gradient(45deg, #ff8f00, #000000);'
  +'}'
  +'.frameShadow{'
    +'position:absolute;'
    +'top:0px;'
    +'width: 200px;'
    +'height: 300px;'
    +'background: inherit;'
    +'filter: blur(30px);'
  +'}'
  +'.frameBackground{'
    +'position:absolute;'
    +'top:0px;'
    +'width: 200px;'
    +'height: 300px;'
    +'background: inherit;'
  +'}'
  +'.container .frame:nth-child(1){'
    +'background: linear-gradient(45deg, #ff8f00, #000000);'
  +'}'
  +'.container .frame:nth-child(2){'
    +'background: linear-gradient(45deg, #ffFFFF, #000000);'
    +'left:250px;'
  +'}'
  +'.container .frame:nth-child(3){'
    +'background: linear-gradient(45deg, #ff02a3, #FFFFFF);'
    +'left:500px;'
  +'}'   
  +'</style>'
  +'<h1>tipos de gradientes para el background</h1><br>'
  +'<h3>Linear Gradient</h3>'
  +'<div style="overflow:auto">'
    +'<table>'
      +'<tr>'
        +'<td><div class="gradient linear_gradient1"></div>.gradient<br>.linear_gradient1</td>'
        +'<td><div class="gradient linear_gradient2"></div>.gradient<br>.linear_gradient2</td>'
        +'<td><div class="gradient linear_gradient3"></div>.gradient<br>.linear_gradient3</td>'
        +'<td><div class="gradient linear_gradient4"></div>.gradient<br>.linear_gradient4</td>'
      +'</tr>'
      +'<tr>'
        +'<td><div class="gradient linear_gradient1 circular"></div>.gradient<br>.linear_gradient1<br>.circular</td>'
        +'<td><div class="gradient linear_gradient2 circular"></div>.gradient<br>.linear_gradient2<br>.circular</td>'
        +'<td><div class="gradient linear_gradient3 circular"></div>.gradient<br>.linear_gradient3<br>.circular</td>'
        +'<td><div class="gradient linear_gradient4 circular"></div>.gradient<br>.linear_gradient4<br>.circular</td>'
      +'</tr>'
    +'</table>'
  +'</div>'
  +'<div class="panelCodeView" style="overflow:auto">'
    +'<div class="titleCodeView">CSS</div>'
    +'<pre class="codeView">'
      +'<y>.gradient{</y>\n'
        +'  <b>height</b>:<o>100px</o>;\n'
        +'  <b>width</b>:<o>100px</o>;\n'
      +'<y>}</y>\n\n'
      +'<y>.circular{</y>\n'
        +'  <b>border-radius</b>:<o>50px</o>;\n'
      +'<y>}</y>\n\n'
      +'<y>.linear_gradient1{</y>\n'
        +'  <b>background</b>:<o>linear-gradient(316deg, <back style="background:#ff0058;color:white">#ff0058</back>,<back style="background:#03a9f4;color:black">#03a9f4</back>)</o>;\n'
      +'<y>}</y>\n\n'
      +'<y>.linear_gradient2{</y>\n'
        +'  <b>background</b>:<o>linear-gradient(316deg, <back style="background:#f05bf1;color:black">#f05bf1</back>,<back style="background:#22b2e9;color:black">#22b2e9</back>)</o>;\n'
      +'<y>}</y>\n\n'
      +'<y>.linear_gradient3{</y>\n'
        +'  <b>background</b>:<o>linear-gradient(45deg, <back style="background:#ffbc00;color:black">#ffbc00</back>,<back style="background:#ff0058;color:black">#ff0058</back>)</o>;\n'
      +'<y>}</y>\n\n'
      +'<y>.linear_gradient4{</y>\n'
        +'  <b>background</b>:<o>linear-gradient(316deg, <back style="background:#4dff03;color:black">#4dff03</back>,<back style="background:#03a9f4;color:black">#03a9f4</back>)</o>;\n'
      +'<y>}</y>\n\n'
    +'</pre>'
  +'</div>'
  +'<br><br>'
  +'<h3>Radial Gradient</h3>'
  +'<div style="overflow:auto">'
    +'<table>'
      +'<tr>'
        +'<td><div class="gradient radial_gradient1"></div></td>'
        +'<td><div class="gradient radial_gradient2"></div></td>'
        +'<td><div class="gradient radial_gradient3"></div></td>'
        +'<td><div class="gradient radial_gradient4"></div></td>'
      +'</tr>'
      +'<tr>'
        +'<td><div class="gradient radial_gradient1 circular"></div></td>'
        +'<td><div class="gradient radial_gradient2 circular"></div></td>'
        +'<td><div class="gradient radial_gradient3 circular"></div></td>'
        +'<td><div class="gradient radial_gradient4 circular"></div></td>'
      +'</tr>'
    +'</table>'
  +'</div>'
  +'<div class="panelCodeView" style="overflow:auto">'
    +'<div class="titleCodeView">CSS</div>'
    +'<pre class="codeView">'
      +'<y>.gradient{</y>\n'
        +'  <b>height</b>:<o>100px</o>;\n'
        +'  <b>width</b>:<o>100px</o>;\n'
      +'<y>}</y>\n\n'
      +'<y>.circular{</y>\n'
        +'  <b>border-radius</b>:<o>50px</o>;\n'
      +'<y>}</y>\n\n'
      +'<y>.radial_gradient1{</y>\n'
        +'  <b>background</b>:<o>radial-gradient(<back style="background:#ff0058;color:white">#ff0058</back>,<back style="background:#03a9f4;color:black">#03a9f4</back>)</o>;\n'
      +'<y>}</y>\n\n'
      +'<y>.radial_gradient2{</y>\n'
        +'  <b>background</b>:<o>radial-gradient(316deg, <back style="background:#f05bf1;color:black">#f05bf1</back>,<back style="background:#03a9f4;color:black">#03a9f4</back>)</o>;\n'
      +'<y>}</y>\n\n'
      +'<y>.radial_gradient3{</y>\n'
        +'  <b>background</b>:<o>radial-gradient(316deg, <back style="background:#ffbc00;color:black">#ffbc00</back>,<back style="background:#ff0058;color:black">#ff0058</back>)</o>;\n'
      +'<y>}</y>\n\n'
      +'<y>.radial_gradient4{</y>\n'
        +'  <b>background</b>:<o>radial-gradient(316deg, <back style="background:#4dff03;color:black">#4dff03</back>,<back style="background:#03a9f4;color:black">#03a9f4</back>)</o>;\n'
      +'<y>}</y>\n\n'
    +'</pre>'
  +'</div>'
  +'<br><br>'
  +'<h3>Conic Gradient</h3>'
  +'<div style="overflow:auto">'
    +'<table>'
      +'<tr>'
        +'<td><div class="gradient conic_gradient1 circular"></div></td>'
        +'<td><div class="gradient conic_gradient2 circular"></div></td>'
      +'</tr>'
    +'</table>'
  +'</div>'
  +'<div class="panelCodeView" style="overflow:auto">'
    +'<div class="titleCodeView">CSS</div>'
    +'<pre class="codeView">'
      +'<y>.gradient{</y>\n'
        +'  <b>height</b>:<o>100px</o>;\n'
        +'  <b>width</b>:<o>100px</o>;\n'
      +'<y>}</y>\n\n'
      +'<y>.circular{</y>\n'
        +'  <b>border-radius</b>:<o>50px</o>;\n'
      +'<y>}</y>\n\n'
      +'<y>.conic_gradient1{</y>\n'
        +'  <b>background</b>:<o>conic-gradient(<back style="background:#5e5e5e;color:white">#5e5e5e</back>, <back style="background:#3a3a3a;color:white">#3a3a3a</back>, <back style="background:#181818;color:white">#181818</back>,<back style="background:#181818;color:white">#181818</back>, <back style="background:#3a3a3a;color:white">#3a3a3a</back>,<back style="background:#5e5e5e;color:white">#5e5e5e</back>,<back style="background:#3a3a3a;color:white">#3a3a3a</back>,<back style="background:#181818;color:white">#181818</back>,<back style="background:#181818;color:white">#181818</back>,<back style="background:#3a3a3a;color:white">#3a3a3a</back>,<back style="background:#5e5e5e;color:white">#5e5e5e</back>);</o>'
      +'<y>}</y>\n\n'
      +'<y>.conic_gradient2{</y>\n'
        +'  <b>background</b>:<o>conic-gradient(<back style="background:#c5dee5;color:white">#c5dee5</back>, <back style="background:#79a0ab;color:white">#79a0ab</back>, <back style="background:#607e87;color:white">#607e87</back>,<back style="background:#607e87;color:white">#607e87</back>, <back style="background:#79a0ab;color:white">#79a0ab</back>,<back style="background:#C5DDE5;color:white">#C5DDE5</back>,<back style="background:#79a0ab;color:white">#79a0ab</back>,<back style="background:#607e87;color:white">#607e87</back>,<back style="background:#607e87;color:white">#607e87</back>,<back style="background:#79a0ab;color:white">#79a0ab</back>,<back style="background:#c5dee5;color:white">#c5dee5</back>);</o>'
      +'<y>}</y>\n\n'
    +'</pre>'
  +'</div>'
  +'<br><br>'
  +'<h3>Shadow Gradient</h3>'
  +'<div style="overflow:auto">'
    +'<div class="container">'
      +'<div class="frame">'
        +'<div class="frameShadow"></div>'
        +'<div class="frameBackground"></div>'
      +'</div>'
      +'<div class="frame">'
        +'<div class="frameShadow"></div>'
        +'<div class="frameBackground"></div>'
      +'</div>'
      +'<div class="frame">'
        +'<div class="frameShadow"></div>'
        +'<div class="frameBackground"></div>'
      +'</div>'
    +'</div>'
  +'</div>'
  +'<div class="panelCodeView" style="overflow:auto">'
    +'<div class="titleCodeView">HTML</div>'
    +'<pre class="codeView">'
      +'&lt;<b>div</b> <b>class</b>=<o>"frame"</o>&gt;\n'
      +'  &lt;<b>div</b> <b>class</b>=<o>"frameShadow"</o>&gt;&lt;/<b>div</b>&gt;\n'
      +'  &lt;<b>div</b> <b>class</b>=<o>"frameBackground"</o>&gt;&lt;/<b>div</b>&gt;\n'
      +'&lt;/<b>div</b>&gt;'
    +'</pre>'
  +'</div>'
  +'<div class="panelCodeView" style="overflow:auto">'
    +'<div class="titleCodeView">CSS</div>'
    +'<pre class="codeView">'
      +'<y>.frame{</y>\n'
        +'  <b>position</b>:<o>relative</o>;\n'
        +'  <b>background</b>:<o>linear-gradient(45deg, #ff8f00, #000000)</o>;\n'
      +'<y>}</y>\n'
      +'<y>.frameShadow{</y>\n'
        +'  <b>position</b>:<o>absolute</o>;\n'
        +'  <b>top</b>:<o>0px</o>;\n'
        +'  <b>width</b>:<o>200px</o>;\n'
        +'  <b>height</b>:<o>300px</o>;\n'
        +'  <b>background</b>:<o>inherit</o>;\n'
        +'  <b>filter</b>:<o>blur(30px)</o>;\n'
      +'<y>}</y>\n'
      +'<y>.frameBackground{</y>\n'
        +'  <b>position</b>:<o>absolute</o>;\n'
        +'  <b>top</b>:<o>0px</o>;\n'
        +'  <b>width</b>:<o>200px</o>;\n'
        +'  <b>height</b>:<o>300px</o>;\n'
        +'  <b>background</b>:<o>inherit</o>;\n'
      +'<y>}</y>\n'
      +'<y>.frame:nth-child(1){</y>\n'
        +'<b> background</b>:<o>linear-gradient(45deg, #ff8f00, #000000)</o>;\n'
      +'<y>}</y>\n'
      +'<y>.frame:nth-child(2){</y>\n'
        +'<b> background</b>:<o>linear-gradient(45deg, #ffFFFF, #000000)</o>;\n'
      +'<y>}</y>\n'
      +'<y>.frame:nth-child(3){</y>\n'
        +'<b> background</b>:<o>linear-gradient(45deg, #ff02a3, #FFFFFF)</o>;\n'
      +'<y>}</y>\n'   
    +'</pre>'
  +'</div>'
  ;
  
  $q("#pageRight").innerHTML = htmlContentPageRight;    
}

function centerDivSelected(){
  let htmlContentPageRight = '<style>'
  +'.parent{'
    +'display:grid;'
    +'place-items:center;'
    +'background:#aabdcd;'
    +'width: 99%;'
    +'height: 200px;'
    +'border: 2px solid #4c4cff;'
  +'}'
  +'.child{'
    +'background:#6f5ecf;'
    +'width: 50%;'
    +'height: 50%;'
    +'border: 2px solid #4c4cff;'
  +'}'
  +'</style>'
  +'<h1>Centrar un Div (o cualquier otro elemento)</h1><br>'
  +'<h3>Utilizando display:grid</h3>'
  +'<div style="overflow:auto">'
    +'<div class="parent">'
      +'<div class="child">'
      +'</div>'
    +'</div>'
  +'</div>'
  +'<div class="panelCodeView" style="overflow:auto">'
    +'<div class="titleCodeView">HTML</div>'
    +'<pre class="codeView">'
      +'&lt;<b>div</b> <b>class</b>=<o>"parent"</o>&gt;\n'
      +'  &lt;<b>div</b> <b>class</b>=<o>"child"</o>&gt;&lt;/<b>div</b>&gt;\n'
      +'&lt;/<b>div</b>&gt;'
    +'</pre>'
  +'</div>'
  +'<div class="panelCodeView" style="overflow:auto">'
    +'<div class="titleCodeView">CSS</div>'
    +'<pre class="codeView">'
      +'<y>.parent{</y>\n'
        +'  <b>display</b>:<o>grid</o>;\n'
        +'  <b>place-items</b>:<o>center</o>;\n'
        +'  <b>background</b>:<back style="background:#aabdcd;color:black;">#aabdcd</back>;\n'
      +'<y>}</y>\n\n'
      +'<y>.child{</y>\n'
        +'  <b>background</b>:<back style="background:#6f5ecf;color:black;">#6f5ecf</back>;\n'
      +'<y>}</y>\n\n'
    +'</pre>'
  +'</div>'
  
  $q("#pageRight").innerHTML = htmlContentPageRight;  
}

function borderGradientSelected(){
  let htmlContentPageRight = '<style>'
    +'.border{'
      +'height: 300px;'
      +'width: 200px;'
      +'display: grid;'
      +'place-items: center;'
      +'background: black;'
      +'position: relative;'
      +'overflow: hidden;'
    +'}'
    +'.border:before{'
      +'content: "";'
      +'height: 150%;'
      +'width: 200%;'
      +'background: conic-gradient(#ff1b1b, #2828ff, #25c525, #ffff2b, #ffb224,#ff1b1b);'
      +'display: grid;'
      +'place-items: center;'
      +'animation: spin 2s infinite linear;'
    +'}'
    +'.front{'
      +'background: #1a1a1a;'
      +'height: 95%;'
      +'width: 95%;'
      +'position: absolute;'
    +'}'
    +'@keyframes spin {'
      +'100% {'
        +'transform: rotate(-360deg);'
      +'}'
    +'}'
  +'</style>'
  +'<h1>Bordes con colores gradientes</h1><br>'
  +'<h3>Gradiente arcoíris con animación</h3>'
  +'<div style="overflow:auto">'
    +'<div class="border">'
      +'<div class="front"></div>'
    +'</div>'
  +'</div>'
  +'<div class="panelCodeView" style="overflow:auto">'
    +'<div class="titleCodeView">HTML</div>'
    +'<pre class="codeView">'
      +'&lt;<b>div</b> <b>class</b>=<o>"border"</o>&gt;\n'
      +'  &lt;<b>div</b> <b>class</b>=<o>"front"</o>&gt;&lt;/<b>div</b>&gt;\n'
      +'&lt;/<b>div</b>&gt;'
    +'</pre>'
  +'</div>'
  +'<div class="panelCodeView" style="overflow:auto">'
    +'<div class="titleCodeView">CSS</div>'
    +'<pre class="codeView">'
      +'<y>.border{</y>\n'
        +'  <b>height</b>:<o>300px</o>;\n'
        +'  <b>width</b>:<o>200px</o>;\n'
        +'  <b>display</b>:<o>grid</o>;\n'
        +'  <b>place-items</b>:<o>center</o>;\n'
        +'  <b>background</b>:<back style="background=#1a1a1a;color:white;">#1a1a1a</back>;\n'
        +'  <b>position</b>:<o>relative</o>;\n'
        +'  <b>overflow</b>:<o>hidden</o>;\n'
      +'<y>}</y>\n\n'
      +'<y>.border:before{</y>\n'
        +'  <b>content</b>: <o>"";\n'
        +'  <b>height</b>: <o>150%;\n'
        +'  <b>width</b>: <o>200%;\n'
        +'  <b>background</b>: <o>conic-gradient(<back style="background:#ff1b1b;color:black;">#ff1b1b</back>,<back style="background:#2828ff;color:white;">#2828ff</back>, <back style="background:#25c525;color:black;">#25c525</back>, <back style="background:#ffff2b;color:black;">#ffff2b</back>, <back style="background:#ffb224;color:black;">#ffb224</back>,<back style="background:#ff1b1b;color:black;">#ff1b1b</back>)</o>;\n'
        +'  <b>display</b>: <o>grid</o>;\n'
        +'  <b>place-items</b>: <o>center</o>;\n'
        +'  <b>animation</b>: <o>spin 2s infinite linear</o>;\n'
      +'<y>}</y>\n\n'
      +'<f>@keyframes</f> <b>spin</b> <y>{</y>\n'
        +'  <b>100%</b> <y>{</y>\n'
          +'    <b>transform</b>: <o>rotate(-360deg)</o>;\n'
        +'  <y>}</y>\n'
      +'<y>}</y>\n\n'
      +'<y>.front{</y>\n'
        +'  <b>background</b>:<back style="background:#1a1a1a;color:white;">#1a1a1a</back>;\n'
        +'  <b>height</b>:<o>95%</o>;\n'
        +'  <b>width</b>:<o>95%</o>;\n'
        +'  <b>position</b>:<o>absolute</o>;\n'
      +'<y>}</y>\n\n'
    +'</pre>'
  +'</div>'
  
  $q("#pageRight").innerHTML = htmlContentPageRight;  

}